active_dataset: mt_syn #choose the dataset here

paths:
  gt_dir: "/mnt/md0/rajalakshmi/Unet_seg/teasar_refactoring/st_syn/evaluation_refactoring/GT/" #path to GT graph folder
  pred_dir: "/mnt/md0/rajalakshmi/Unet_seg/teasar_refactoring/st_syn/evaluation_refactoring/pred/" #path to pred graph
  main_script: "main.py"

evaluation_by_dataset:
  st_syn:
    matching: "hierarchical"
    matching_dist: "fixed"
    candidate_selection: "ball"
    max_distance: 1.5
    resample_to_gt: true

  mt_syn:
    matching: "hierarchical"
    matching_dist: "fixed"
    candidate_selection: "query"
    max_distance: 10.0
    resample_to_gt: false

  parse2022:
    matching: "hierarchical"
    matching_dist: "fixed"
    candidate_selection: "ball"
    max_distance: 1.5
    resample_to_gt: false

  micro_ct:
    matching: "hierarchical"
    matching_dist: "fixed"
    candidate_selection: "ball"
    max_distance: 5.0
    resample_to_gt: true